Assocation Rule Mining Using Apriori Algorithm

In [1]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Collecting scipy>=1.16.3 (from mlxtend)
  Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: numpy>=2.3.5 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlxtend) (2.3.5)
Collecting pandas>=2.3.3 (from mlxtend)
  Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Using cached matplotlib-3.11.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: joblib>=1.5.2 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (24.2)
Requirement already satisfied: pillow>=9 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Downloading mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 1.1 MB/s eta 0:00:01
   --------------- ------------------------ 0.5/1.4 MB 1.1 MB/s eta 0:00:01
   --------------- ------------------------ 0.5/1.4 MB 1.1 MB/s eta 0:00:01
   ----------------------- ---------------- 0.8/1.4 MB 692.0 kB/s eta 0:00:01
   ----------------------- ---------------- 0.8/1.4 MB 692.0 kB/s eta 0:00:01
   ----------------------- ---------------- 0.8/1.4 MB 692.0 kB/s eta 0:00:01
   ----------------------- ---------------- 0.8/1.4 MB 692.0 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 451.6 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 451.6 kB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 451.6 kB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 496.1 kB/s  0:00:02
Using cached matplotlib-3.11.1-cp313-cp313-win_amd64.whl (9.3 MB)
Downloading pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.8 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.8 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.8 MB 712.9 kB/s eta 0:00:14
   --- ------------------------------------ 0.8/9.8 MB 1.0 MB/s eta 0:00:09
   --- ------------------------------------ 0.8/9.8 MB 1.0 MB/s eta 0:00:09
   --- ------------------------------------ 0.8/9.8 MB 1.0 MB/s eta 0:00:09
   --- ------------------------------------ 0.8/9.8 MB 1.0 MB/s eta 0:00:09
   ---- ----------------------------------- 1.0/9.8 MB 586.2 kB/s eta 0:00:15
   ---- ----------------------------------- 1.0/9.8 MB 586.2 kB/s eta 0:00:15
   ----- ---------------------------------- 1.3/9.8 MB 614.4 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.8 MB 614.4 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/9.8 MB 638.2 kB/s eta 0:00:13
   ------- -------------------------------- 1.8/9.8 MB 710.6 kB/s eta 0:00:12
   -------- ------------------------------- 2.1/9.8 MB 755.4 kB/s eta 0:00:11
   --------- ------------------------------ 2.4/9.8 MB 797.1 kB/s eta 0:00:10
   ---------- ----------------------------- 2.6/9.8 MB 826.0 kB/s eta 0:00:09
   ----------- ---------------------------- 2.9/9.8 MB 839.8 kB/s eta 0:00:09
   ------------ --------------------------- 3.1/9.8 MB 841.9 kB/s eta 0:00:08
   ------------ --------------------------- 3.1/9.8 MB 841.9 kB/s eta 0:00:08
   -------------- ------------------------- 3.7/9.8 MB 890.7 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.8 MB 980.4 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.8 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 6.0/9.8 MB 1.3 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.8 MB 1.4 MB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.8 MB 1.5 MB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.8 MB 1.6 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.8 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 9.8/9.8 MB 1.8 MB/s  0:00:05
Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
Downloading scipy-1.18.1-cp313-cp313-win_amd64.whl (36.6 MB)
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
    --------------------------------------- 0.5/36.6 MB 3.0 MB/s eta 0:00:12
   - -------------------------------------- 1.3/36.6 MB 3.6 MB/s eta 0:00:10
   -- ------------------------------------- 1.8/36.6 MB 3.5 MB/s eta 0:00:10
   --- ------------------------------------ 2.9/36.6 MB 3.7 MB/s eta 0:00:10
   ---- ----------------------------------- 3.9/36.6 MB 3.9 MB/s eta 0:00:09
   ----- ---------------------------------- 4.7/36.6 MB 4.1 MB/s eta 0:00:08
   ------ --------------------------------- 5.8/36.6 MB 4.2 MB/s eta 0:00:08
   ------- -------------------------------- 6.8/36.6 MB 4.2 MB/s eta 0:00:08
   -------- ------------------------------- 7.6/36.6 MB 4.2 MB/s eta 0:00:07
   -------- ------------------------------- 8.1/36.6 MB 4.0 MB/s eta 0:00:08
   --------- ------------------------------ 8.9/36.6 MB 4.1 MB/s eta 0:00:07
   ---------- ----------------------------- 9.7/36.6 MB 4.0 MB/s eta 0:00:07
   ----------- ---------------------------- 10.7/36.6 MB 4.0 MB/s eta 0:00:07
   ------------ --------------------------- 11.5/36.6 MB 4.0 MB/s eta 0:00:07
   ------------- -------------------------- 12.1/36.6 MB 4.0 MB/s eta 0:00:07
   -------------- ------------------------- 12.8/36.6 MB 4.0 MB/s eta 0:00:06
   -------------- ------------------------- 13.4/36.6 MB 4.0 MB/s eta 0:00:06
   --------------- ------------------------ 13.9/36.6 MB 3.8 MB/s eta 0:00:06
   ---------------- ----------------------- 14.7/36.6 MB 3.8 MB/s eta 0:00:06
   ---------------- ----------------------- 15.5/36.6 MB 3.8 MB/s eta 0:00:06
   ----------------- ---------------------- 16.3/36.6 MB 3.8 MB/s eta 0:00:06
   ------------------ --------------------- 17.0/36.6 MB 3.8 MB/s eta 0:00:06
   ------------------- -------------------- 17.8/36.6 MB 3.8 MB/s eta 0:00:05
   -------------------- ------------------- 18.6/36.6 MB 3.8 MB/s eta 0:00:05
   -------------------- ------------------- 18.9/36.6 MB 3.8 MB/s eta 0:00:05
   --------------------- ------------------ 19.4/36.6 MB 3.7 MB/s eta 0:00:05
   --------------------- ------------------ 19.9/36.6 MB 3.6 MB/s eta 0:00:05
   ---------------------- ----------------- 20.7/36.6 MB 3.6 MB/s eta 0:00:05
   ----------------------- ---------------- 21.2/36.6 MB 3.6 MB/s eta 0:00:05
   ----------------------- ---------------- 21.8/36.6 MB 3.6 MB/s eta 0:00:05
   ------------------------ --------------- 22.5/36.6 MB 3.5 MB/s eta 0:00:04
   ------------------------- -------------- 23.1/36.6 MB 3.5 MB/s eta 0:00:04
   ------------------------- -------------- 23.6/36.6 MB 3.5 MB/s eta 0:00:04
   -------------------------- ------------- 24.6/36.6 MB 3.5 MB/s eta 0:00:04
   --------------------------- ------------ 25.2/36.6 MB 3.5 MB/s eta 0:00:04
   ---------------------------- ----------- 25.7/36.6 MB 3.5 MB/s eta 0:00:04
   ---------------------------- ----------- 26.5/36.6 MB 3.5 MB/s eta 0:00:03
   ----------------------------- ---------- 27.0/36.6 MB 3.5 MB/s eta 0:00:03
   ------------------------------ --------- 27.8/36.6 MB 3.5 MB/s eta 0:00:03
   ------------------------------ --------- 28.3/36.6 MB 3.5 MB/s eta 0:00:03
   ------------------------------- -------- 28.8/36.6 MB 3.4 MB/s eta 0:00:03
   -------------------------------- ------- 29.4/36.6 MB 3.4 MB/s eta 0:00:03
   -------------------------------- ------- 30.1/36.6 MB 3.4 MB/s eta 0:00:02
   --------------------------------- ------ 30.4/36.6 MB 3.4 MB/s eta 0:00:02
   --------------------------------- ------ 30.9/36.6 MB 3.4 MB/s eta 0:00:02
   ---------------------------------- ----- 31.5/36.6 MB 3.4 MB/s eta 0:00:02
   ----------------------------------- ---- 32.2/36.6 MB 3.4 MB/s eta 0:00:02
   ------------------------------------ --- 33.0/36.6 MB 3.4 MB/s eta 0:00:02
   ------------------------------------ --- 33.8/36.6 MB 3.4 MB/s eta 0:00:01
   ------------------------------------- -- 34.6/36.6 MB 3.4 MB/s eta 0:00:01
   -------------------------------------- - 35.4/36.6 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  35.9/36.6 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------  36.4/36.6 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 36.6/36.6 MB 3.4 MB/s  0:00:10
Installing collected packages: scipy, scikit-learn, pandas, matplotlib, mlxtend

  Attempting uninstall: scipy

    Found existing installation: scipy 1.16.2

   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
    Uninstalling scipy-1.16.2:
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
      Successfully uninstalled scipy-1.16.2
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\Users\\Rathishan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\scipy-1.18.1.dist-info\\INSTALLERpb_kyl6j.tmp'


[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
pip install mlxtend

Collecting mlxtend
  Using cached mlxtend-0.25.0-py3-none-any.whl.metadata (7.4 kB)
Collecting scipy>=1.16.3 (from mlxtend)
  Using cached scipy-1.18.1-cp313-cp313-win_amd64.whl.metadata (61 kB)
Requirement already satisfied: numpy>=2.3.5 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlxtend) (2.3.5)
Collecting pandas>=2.3.3 (from mlxtend)
  Using cached pandas-3.0.5-cp313-cp313-win_amd64.whl.metadata (19 kB)
Collecting scikit-learn>=1.8.0 (from mlxtend)
  Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Collecting matplotlib>=3.10.8 (from mlxtend)
  Using cached matplotlib-3.11.1-cp313-cp313-win_amd64.whl.metadata (80 kB)
Requirement already satisfied: joblib>=1.5.2 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (24.2)
Requirement already satisfied: pillow>=9 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.4)
Requirement already satisfied: python-dateutil>=2.7 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)
Requirement already satisfied: six>=1.5 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.6.0)
Using cached mlxtend-0.25.0-py3-none-any.whl (1.4 MB)
Using cached matplotlib-3.11.1-cp313-cp313-win_amd64.whl (9.3 MB)
Using cached pandas-3.0.5-cp313-cp313-win_amd64.whl (9.8 MB)
Using cached scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
Using cached scipy-1.18.1-cp313-cp313-win_amd64.whl (36.6 MB)
Installing collected packages: scipy, scikit-learn, pandas, matplotlib, mlxtend

  Attempting uninstall: scipy

    Found existing installation: scipy 1.16.2

   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
    Uninstalling scipy-1.16.2:
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
      Successfully uninstalled scipy-1.16.2
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
  Attempting uninstall: scikit-learn
   ---------------------------------------- 0/5 [scipy]
    Found existing installation: scikit-learn 1.7.2
   ---------------------------------------- 0/5 [scipy]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
    Uninstalling scikit-learn-1.7.2:
   -------- ------------------------------- 1/5 [scikit-learn]
      Successfully uninstalled scikit-learn-1.7.2
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]
   -------- ------------------------------- 1/5 [scikit-learn]

WARNING: Ignoring invalid distribution ~cipy (c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~cipy (c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages)
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages\~cipy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages\~cipy'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages\~klearn'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages\~andas'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages\~atplotlib'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.0.1 requires aiofiles<25.0,>=22.0, but you have aiofiles 25.1.0 which is incompatible.
gradio 6.0.1 requires pandas<3.0,>=1.0, but you have pandas 3.0.5 which is incompatible.
gradio 6.0.1 requires pydantic<=2.12.4,>=2.11.10, but you have pydantic 2.13.4 which is incompatible.
gradio 6.0.1 requires starlette<1.0,>=0.40.0, but you have starlette 1.3.1 which is incompatible.
streamlit 1.50.0 requires pandas<3,>=1.4.0, but you have pandas 3.0.5 which is incompatible.
WARNING: Ignoring invalid distribution ~cipy (c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
%pip install -U pandas mlxtend scikit-learn

Requirement already satisfied: pandas in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.5)
Requirement already satisfied: mlxtend in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (0.25.0)
Requirement already satisfied: scikit-learn in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.16.3 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlxtend) (1.18.1)
Requirement already satisfied: matplotlib>=3.10.8 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlxtend) (3.11.1)
Requirement already satisfied: joblib>=1.5.2 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from mlxtend) (1.5.2)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.7.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (24.2)
Requirement already satisfied: pillow>=9 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (11.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.4)
Requirement already satisfied: six>=1.5 in c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~cipy (c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~cipy (c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages)
WARNING: Ignoring invalid distribution ~cipy (c:\Users\Rathishan\AppData\Local\Programs\Python\Python313\Lib\site-packages)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [6]:
data=pd.read_csv('C://Users//Rathishan//Desktop//Git//machine-learning-portfolio//machine-learning-portfolio//dataset//groceries.csv')

In [7]:
data.head()

,1,2,3,4,5,6,7,8,9
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN

In [19]:
baskets_sets = data.stack().str.get_dummies().groupby(level=0).sum()

In [20]:
baskets_sets.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [23]:
baskets_sets_bool = baskets_sets.astype('bool')
apriori(baskets_sets_bool, min_support=0.02, use_colnames=True)

      support                                         itemsets
0    0.028155                                       (UHT-milk)
1    0.054369                                           (beef)
2    0.032039                                        (berries)
3    0.027508                                      (beverages)
4    0.072492                                   (bottled beer)
..        ...                                              ...
105  0.022977                         (tropical fruit, yogurt)
106  0.033981                 (whole milk, whipped/sour cream)
107  0.055987                             (whole milk, yogurt)
108  0.022977  (whole milk, other vegetables, root vegetables)
109  0.022977           (whole milk, other vegetables, yogurt)

[110 rows x 2 columns]

In [29]:
df_combo = baskets_sets.astype('bool')
frequent_itemsets = apriori(df_combo, min_support=0.002, use_colnames=True)
frequent_itemsets['length']=frequent_itemsets['itemsets'].apply(lambda x : len(x))
frequent_itemsets

       support                                           itemsets  length
0     0.007120                            (Instant food products)       1
1     0.028155                                         (UHT-milk)       1
2     0.002913                                 (abrasive cleaner)       1
3     0.003560                                 (artif. sweetener)       1
4     0.014887                                    (baking powder)       1
...        ...                                                ...     ...
2313  0.002265  (root vegetables, whole milk, other vegetables...       5
2314  0.002589  (whipped/sour cream, whole milk, other vegetab...       5
2315  0.002265  (whole milk, other vegetables, pip fruit, yogu...       5
2316  0.002265  (root vegetables, whole milk, tropical fruit, ...       5
2317  0.002265  (whole milk, tropical fruit, other vegetables,...       5

[2318 rows x 3 columns]

In [30]:
frequent_itemsets[ (frequent_itemsets['length'] >= 3)]

       support                                           itemsets  length
1260  0.002589        (other vegetables, bottled water, UHT-milk)       3
1261  0.002265                    (soda, bottled water, UHT-milk)       3
1262  0.002589      (whole milk, other vegetables, baking powder)       3
1263  0.002265    (whole milk, baking powder, whipped/sour cream)       3
1264  0.002589                        (whole milk, berries, beef)       3
...        ...                                                ...     ...
2313  0.002265  (root vegetables, whole milk, other vegetables...       5
2314  0.002589  (whipped/sour cream, whole milk, other vegetab...       5
2315  0.002265  (whole milk, other vegetables, pip fruit, yogu...       5
2316  0.002265  (root vegetables, whole milk, tropical fruit, ...       5
2317  0.002265  (whole milk, tropical fruit, other vegetables,...       5

[1058 rows x 3 columns]

In [ ]:
rules=association_rules(
    frequent_itemsets,
    metric='confidence',
    min_threshold=0.9
    )
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"(curd, hamburger meat)",(whole milk),0.003236,0.256634,0.003236,1.000000,3.896595,1.0,0.002406,inf,0.745779,0.012610,1.000000,0.506305
1,"(root vegetables, frozen fish)",(whole milk),0.002265,0.256634,0.002265,1.000000,3.896595,1.0,0.001684,inf,0.745054,0.008827,1.000000,0.504414
2,"(sausage, soda, bottled water)",(yogurt),0.003560,0.136893,0.003236,0.909091,6.640877,1.0,0.002749,9.494175,0.852452,0.023585,0.894672,0.466366
3,"(sausage, bottled water, yogurt)",(soda),0.003560,0.159223,0.003236,0.909091,5.709534,1.0,0.002669,9.248544,0.827801,0.020284,0.891875,0.464708
4,"(whole milk, pip fruit, butter)",(other vegetables),0.003560,0.192557,0.003236,0.909091,4.721161,1.0,0.002551,8.881877,0.791004,0.016779,0.887411,0.462949

In [33]:
rules=association_rules(
    frequent_itemsets,
    metric='lift',
    min_threshold=1
)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(other vegetables),(Instant food products),0.192557,0.007120,0.002265,0.011765,1.652406,1.0,0.000894,1.004700,0.488978,0.011475,0.004678,0.164973
1,(Instant food products),(other vegetables),0.007120,0.192557,0.002265,0.318182,1.652406,1.0,0.000894,1.184250,0.397653,0.011475,0.155584,0.164973
2,(root vegetables),(Instant food products),0.110032,0.007120,0.002265,0.020588,2.891711,1.0,0.001482,1.013752,0.735065,0.019718,0.013565,0.169385
3,(Instant food products),(root vegetables),0.007120,0.110032,0.002265,0.318182,2.891711,1.0,0.001482,1.305286,0.658875,0.019718,0.233884,0.169385
4,(bottled water),(UHT-milk),0.111974,0.028155,0.006472,0.057803,2.053020,1.0,0.003320,1.031467,0.577587,0.048426,0.030507,0.143844

In [34]:

rules[(rules['lift']>=5) & (rules['confidence']>= 0.8)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
7110,"(sausage, soda, bottled water)",(yogurt),0.003560,0.136893,0.003236,0.909091,6.640877,1.0,0.002749,9.494175,0.852452,0.023585,0.894672,0.466366
7112,"(sausage, bottled water, yogurt)",(soda),0.003560,0.159223,0.003236,0.909091,5.709534,1.0,0.002669,9.248544,0.827801,0.020284,0.891875,0.464708
7379,"(sausage, canned beer, rolls/buns)",(shopping bags),0.002589,0.082848,0.002265,0.875000,10.561523,1.0,0.002051,7.337217,0.907667,0.027237,0.863709,0.451172
8131,"(dessert, other vegetables, whipped/sour cream)",(yogurt),0.002913,0.136893,0.002589,0.888889,6.493302,1.0,0.002190,7.767961,0.848466,0.018868,0.871266,0.453901
8186,"(other vegetables, pastry, frankfurter)",(rolls/buns),0.002265,0.194498,0.002265,1.000000,5.141431,1.0,0.001825,inf,0.807331,0.011647,1.000000,0.505824
8314,"(whole milk, hamburger meat, pork)",(other vegetables),0.002589,0.192557,0.002589,1.000000,5.193277,1.0,0.002090,inf,0.809539,0.013445,1.000000,0.506723